import { Logo } from 'Components/Logo';
import { Nav } from 'Components/Nav';
import { Metadata } from 'next';
import React from 'react';
import './global.css';

export const metadata: Metadata = {
	title: 'Sick Fits',
	description: 'Generated by Next.js',
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
	return (
		<html lang="en">
			<head>
				<link rel="shortcut icon" href="/static/favicon.png" />
			</head>
			<body>
				<header>
					<div className="bar">
						<Logo />
					</div>
					<div className="sub-bar">
						<p>Search</p>
					</div>
					<Nav />
				</header>
				{children}
			</body>
		</html>
	);
};

export default RootLayout;
