import { Nav } from 'Components/Nav';
import { Metadata } from 'next';
import Link from 'next/link';
import React from 'react';

export const metadata: Metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
	return (
		<html lang="en">
			<body>
				<header>
					<div className="bar">
						<Link href="/">Sick Fits</Link>
					</div>
					<div className="sub-bar">
						<p>Search</p>
					</div>
					<Nav />
				</header>
				{children}
			</body>
		</html>
	);
};

export default RootLayout;
